export const capabilityStatuses = Object.freeze({
  available: "Repository and test evidence exists on the default branch.",
  partial: "A bounded primitive exists, but the complete product workflow or operational evidence does not.",
  in_review: "Implementation is on a pull request and must not be represented as deployed.",
  planned: "The capability is in scope but no authoritative implementation is claimed.",
  blocked: "A prerequisite contract, security boundary, or control-plane verification is missing.",
});

export const capabilityLedger = Object.freeze({
  contract: "ores.shared-auth.capability-ledger.v1",
  asOf: "2026-09-05",
  issue: "DEN-606",
  disclaimer:
    "This ledger is an evidence map, not a blanket parity claim. A feature is available only when its interface, persistence, authorization, audit, test, and deployment evidence are all present.",
  capabilities: Object.freeze([
    {
      id: "token-exchange",
      domain: "Token exchange and verification",
      status: "available",
      userSurface: "Provider-token exchange, access-token verification, and JWKS discovery.",
      backendEvidence: ["shared-auth-api-server.rs", "shared-auth-clients", "shared-auth-interfaces"],
      nextGate: "Keep issuer, audience, algorithm, expiry, and key-rotation fixtures current across every SDK.",
    },
    {
      id: "protected-introspection",
      domain: "Protected introspection and explicit assurance",
      status: "available",
      userSurface: "Services can require exact audience, scopes, AAL/ACR, AMR, and revocation-aware token state.",
      backendEvidence: ["shared-auth-api-server.rs", "shared-auth-clients"],
      nextGate: "Certify each production resource server with negative audience, scope, credential, and revocation canaries.",
    },
    {
      id: "hosted-auth",
      domain: "Hosted sign-in, sign-up, passwordless, and social identity",
      status: "partial",
      userSurface: "Provider exchange plus email/SMS challenge primitives exist; the complete hosted journey and identity-linking UX are not yet certified.",
      backendEvidence: ["shared-auth-api-server.rs", "shared-auth-clients"],
      nextGate: "Publish typed sign-up, recovery, OAuth callback, identity-linking, abuse-control, and accessibility contracts.",
    },
    {
      id: "mfa",
      domain: "MFA, TOTP, OTP, 3FA, and step-up",
      status: "partial",
      userSurface: "Factor listing, TOTP enrollment/confirmation, email/SMS challenges, and assurance-bearing step-up primitives exist.",
      backendEvidence: ["shared-auth-clients", "3FA-app"],
      nextGate: "Add tenant policy, recovery approvals, reset audit, rate limits, and complete account/admin UI workflows.",
    },
    {
      id: "passkeys",
      domain: "Passkeys and WebAuthn",
      status: "partial",
      userSurface: "Registration and authentication ceremony primitives carry opaque credential JSON without taking custody of biometric templates.",
      backendEvidence: ["shared-auth-clients", "shared-auth-api-server.rs"],
      nextGate: "Certify origin/RP-ID policy, discoverable credentials, device naming, recovery, deletion, and replay-negative fixtures.",
    },
    {
      id: "customer-security-center",
      domain: "Customer account security center",
      status: "in_review",
      userSurface: "MASH, Leptos SSR, and Dioxus SSR views read live introspection, factor, and capability evidence and keep unsupported mutations disabled.",
      backendEvidence: ["shared-auth-web-server.rs#11"],
      nextGate: "Pass format, clippy, test, authorization, cookie, and deployment gates before merge and promotion.",
    },
    {
      id: "organizations",
      domain: "Organizations, tenants, invitations, and RBAC/ABAC",
      status: "planned",
      userSurface: "Organization switching, invitation lifecycle, membership, roles, permissions, and tenant policy are product requirements, not shipped claims.",
      backendEvidence: [],
      nextGate: "Define independent TypeSpec and JSON Schema authorities plus normalized parity, ORM, audit, and authorization tests.",
    },
    {
      id: "enterprise-sso",
      domain: "Enterprise SSO and identity brokering",
      status: "planned",
      userSurface: "SAML and enterprise OIDC connection setup, verified domains, JIT, metadata/key rotation, and test-IdP flows are not yet available.",
      backendEvidence: [],
      nextGate: "Land protocol, connection lifecycle, domain ownership, signing, encryption, rollback, and conformance contracts.",
    },
    {
      id: "directory-sync",
      domain: "SCIM and directory synchronization",
      status: "blocked",
      userSurface: "Provisioning, deprovisioning, groups, role mapping, cursor state, retries, quarantine, and reconciliation UI remain disabled.",
      backendEvidence: [],
      nextGate: "Publish SCIM 2.0 and directory connector authorities with idempotency, tombstones, replay, audit, and dead-letter recovery.",
    },
    {
      id: "sessions-devices",
      domain: "Sessions, devices, trusted-device policy, and global logout",
      status: "planned",
      userSurface: "A complete session/device inventory and cross-region revocation UI is not yet exposed.",
      backendEvidence: [],
      nextGate: "Define bounded search, device trust, compromise response, revocation fan-out, and read-after-write verification.",
    },
    {
      id: "conditional-access",
      domain: "Conditional access, risk signals, and adaptive challenges",
      status: "blocked",
      userSurface: "No deterministic, versioned policy decision/explanation contract is currently available to the user or admin interfaces.",
      backendEvidence: [],
      nextGate: "Specify policy inputs, outputs, exceptions, safe degradation, privacy constraints, and simulation before enforcement controls appear.",
    },
    {
      id: "lifecycle-audit",
      domain: "Lifecycle, audit log, webhooks, and compliance export",
      status: "partial",
      userSurface: "Idempotent admin operation primitives exist, but the complete immutable identity event search/export and webhook-delivery views do not.",
      backendEvidence: ["shared-auth-admin-api-server.rs", "shared-auth-admin-web-server.rs"],
      nextGate: "Add retention-aware event projections, delivery/replay state, signed exports, privacy filters, and redaction tests.",
    },
    {
      id: "admin-operations",
      domain: "Isolated IAM administration",
      status: "in_review",
      userSurface: "The private MASH/Leptos/Dioxus console exposes an evidence ledger behind Shared Auth, admin grants, and trusted-network admission.",
      backendEvidence: ["shared-auth-admin-web-server.rs#6"],
      nextGate: "Pass repository-native gates and certify separate admin identities, secrets, database roles, origins, and ingress in both runtimes.",
    },
    {
      id: "branding-accessibility",
      domain: "Hosted/headless UI, branding, localization, and accessibility",
      status: "partial",
      userSurface: "HTML-first SSR shells exist, but theme tokens, localization catalogs, accessibility conformance, and embeddable headless contracts are incomplete.",
      backendEvidence: ["shared-auth-web-server.rs", "shared-auth-admin-web-server.rs"],
      nextGate: "Add WCAG test gates, keyboard/focus suites, localization contracts, CSP-safe theming, and versioned component APIs.",
    },
    {
      id: "multi-cloud-runtime",
      domain: "Cloudflare, Cloud Run, and Kubernetes resilience",
      status: "partial",
      userSurface: "Exact-host Worker/Terraform groundwork exists; a complete four-service Cloud Run and Kubernetes deployment has not been control-plane certified.",
      backendEvidence: ["shared-auth-infra", "oresoftware/k8s-cluster", "DEN-3067", "DEN-3068"],
      nextGate: "Declare all services and origins, promote immutable digests, then prove DNS, Worker bindings, health failover, isolation, and rollback with read-after-write evidence.",
    },
  ]),
  hostContract: Object.freeze([
    {
      host: "shared-auth.github.io",
      purpose: "Astro marketing and architecture site",
      service: "GitHub Pages artifact",
      exposure: "public",
      certification: "available",
    },
    {
      host: "ores-shared-auth.com",
      purpose: "Public product entry point",
      service: "Cloudflare exact-host gateway",
      exposure: "public",
      certification: "partial",
    },
    {
      host: "auth.ores-shared-auth.com",
      purpose: "Hosted authentication journey",
      service: "customer authentication route",
      exposure: "public",
      certification: "partial",
    },
    {
      host: "user.ores-shared-auth.com",
      purpose: "Customer account and security UI",
      service: "shared-auth-web-server.rs",
      exposure: "public behind Cloudflare",
      certification: "in_review",
    },
    {
      host: "org.ores-shared-auth.com",
      purpose: "Organization and tenant UI",
      service: "shared-auth-web-server.rs",
      exposure: "public behind Cloudflare",
      certification: "planned",
    },
    {
      host: "api.ores-shared-auth.com",
      purpose: "Customer identity API",
      service: "shared-auth-api-server.rs",
      exposure: "public behind Cloudflare",
      certification: "partial",
    },
    {
      host: "admin.ores-shared-auth.com",
      purpose: "Operator IAM console",
      service: "shared-auth-admin-web-server.rs",
      exposure: "private identity-aware ingress only",
      certification: "in_review",
    },
    {
      host: "api-admin.ores-shared-auth.com",
      purpose: "Operator IAM command API",
      service: "shared-auth-admin-api-server.rs",
      exposure: "private service/admin ingress only",
      certification: "partial",
    },
  ]),
  taxonomyReferences: Object.freeze([
    { name: "Clerk", url: "https://clerk.com/docs" },
    { name: "Supabase Auth", url: "https://supabase.com/docs/guides/auth" },
    { name: "Neon Auth", url: "https://neon.com/docs/guides/neon-auth" },
    { name: "Okta/Auth0", url: "https://auth0.com/docs" },
    { name: "WorkOS", url: "https://workos.com/docs" },
    { name: "Stytch", url: "https://stytch.com/docs" },
    { name: "Frontegg", url: "https://developers.frontegg.com" },
    { name: "Microsoft Entra ID", url: "https://learn.microsoft.com/entra/identity/" },
    { name: "Ping Identity", url: "https://docs.pingidentity.com" },
    { name: "OneLogin", url: "https://developers.onelogin.com" },
    { name: "Keycloak", url: "https://www.keycloak.org/documentation" },
    { name: "Ory", url: "https://www.ory.sh/docs" },
    { name: "Logto", url: "https://docs.logto.io" },
    { name: "SuperTokens", url: "https://supertokens.com/docs" },
  ]),
});
